feat: unicorn now can output ising models
cksystemsgroup/unicorn pull request #15
Opened 2022-05-23 11:28 UTC by smml1996

2022-05-23 11:58 UTC, mstarzinger requested changes
Nice! Looks good to me, just some minor comments.

2022-05-23 11:58 UTC, mstarzinger commented on src/cli.rs
> +                    .help("Perform bitblasting of the model")
The description of the option seems to be outdated.

2022-05-23 11:58 UTC, mstarzinger commented on src/unicorn/qubot.rs
> +        for (qubit, coeff) in self.qubo.linear_coefficients.iter() {
This undoes my fix that sorts coefficients by the Qubit number. Can we restore that? I think it is still needed.

2022-05-23 11:58 UTC, mstarzinger commented on src/unicorn/qubot.rs
> +        for (qubit1, edges) in self.qubo.quadratic_coefficients.iter() {
Likewise.

2022-05-23 11:58 UTC, mstarzinger commented on src/unicorn/qubot.rs
> +            for (qubit2, coeff) in edges.iter() {
Likewise.

2022-05-25 09:22 UTC, mstarzinger approved these changes
Nice! Looks good to me.

2022-05-25 09:23 UTC, smml1996 commented
> Nice! Looks good to me.

I just reverted so that I do not erase your changes

2022-05-26 12:53 UTC, merged